name: build-and-publish-playlist

on:
  workflow_dispatch:
  schedule:            # UTC; every 30 min
    - cron:  '11,41 * * * *'

# grant the workflow's GITHUB_TOKEN permission to push to gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install yt-dlp
      run: |
        python -m pip install --upgrade yt-dlp

    - name: Generate playlist.m3u8
      env:
        YT_PLAYLIST_ID: ${{ secrets.YT_PLAYLIST_ID }}   # e.g. PLxxxx
      run: python scripts/build_playlist.py

    - name: Publish to gh-pages
      uses: peaceiris/actions-gh-pages@v4      #   [oai_citation:0‡GitHub](https://github.com/peaceiris/actions-gh-pages?utm_source=chatgpt.com)
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: public
        commit_message: "bot: refresh playlist ($(date -u +'%Y-%m-%d %H:%M'))"