name: build-and-publish-playlist

on:
  workflow_dispatch:
  schedule:            # UTC; every 30 min
    - cron:  '11,41 * * * *'

# grant the workflow's GITHUB_TOKEN permission to push to gh-pages
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v4

      # 2. Install yt‑dlp + ffmpeg
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v3
        with:
          version: latest      # pin if needed

      # 3. Load YouTube cookies from secret (auto‑writes yt‑dlp config)
      - name: Setup yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies@v3
        with:
          cookies: ${{ secrets.YOUTUBE_COOKIES }}

      # 4. Build the playlist
      - name: Generate playlist.m3u8
        env:
          YT_PLAYLIST_ID: ${{ secrets.YT_PLAYLIST_ID }}
          YT_DLP_ARGS: "--geo-bypass --force-ipv4"
        run: python scripts/build_playlist.py

      # 5. Publish to GitHub Pages
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          commit_message: "bot: refresh playlist ($(date -u +'%Y-%m-%d %H:%M'))"

      # 6. Refresh cookies and write back to the secret if they changed
      - name: Update yt-dlp YouTube cookies
        uses: AnimMouse/setup-yt-dlp/cookies/update@v3
        with:
          cookies_secret_name: YOUTUBE_COOKIES
          token: ${{ secrets.GH_PAT }}